//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather_table
    {
        public int ID { get; set; }
        public string city { get; set; }
        public string weather_descr { get; set; }
        public Nullable<int> temp { get; set; }
    }
}
